// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using minerva.planningfkt.models;

#nullable disable

namespace minerva.planningfkt.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828125042_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("minerva.planningfkt.models.AlertDismissal", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Key"));

                    b.Property<DateTime>("DismissedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Key");

                    b.ToTable("AlertDismissals");
                });

            modelBuilder.Entity("minerva.planningfkt.models.AlertMarkedImportant", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Key"));

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SlotId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.ToTable("AlertMarkedImportants");
                });

            modelBuilder.Entity("minerva.planningfkt.models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DocumentAttachedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DocumentFileName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("ModDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModUser")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("minerva.planningfkt.models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModUser")
                        .HasColumnType("int");

                    b.Property<int>("Sorting")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("minerva.planningfkt.models.Therapist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModUser")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("OperatingArea")
                        .HasColumnType("int");

                    b.Property<int>("OvertimeAllowed")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Therapists");
                });

            modelBuilder.Entity("minerva.planningfkt.models.TherapistAbsenceCall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Called")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("TherapistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TherapistAbsenceCalls");
                });

            modelBuilder.Entity("minerva.planningfkt.models.TherapistAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("EndTime")
                        .HasColumnType("int");

                    b.Property<int>("StartTime")
                        .HasColumnType("int");

                    b.Property<int>("TherapistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TherapistId");

                    b.ToTable("TherapistAvailabilities");
                });

            modelBuilder.Entity("minerva.planningfkt.models.Therapy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingCategory")
                        .HasColumnType("int");

                    b.Property<int>("FoglioFirmaStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModUser")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Therapies");
                });

            modelBuilder.Entity("minerva.planningfkt.models.TherapyPacket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Approvatore")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModUser")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PersonName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("TherapyPackets");
                });

            modelBuilder.Entity("minerva.planningfkt.models.TherapyPacketConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DefaultDiscountPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModUser")
                        .HasColumnType("int");

                    b.Property<int>("TherapyTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TherapyTypeId")
                        .IsUnique();

                    b.ToTable("TherapyPacketConfigs");
                });

            modelBuilder.Entity("minerva.planningfkt.models.TherapyPacketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SessionCount")
                        .HasColumnType("int");

                    b.Property<int>("TherapyPacketId")
                        .HasColumnType("int");

                    b.Property<int>("TherapyTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TherapyPacketId");

                    b.HasIndex("TherapyTypeId");

                    b.ToTable("TherapyPacketItems");
                });

            modelBuilder.Entity("minerva.planningfkt.models.TherapyPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ModDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModUser")
                        .HasColumnType("int");

                    b.Property<int>("SessionCount")
                        .HasColumnType("int");

                    b.Property<int>("TherapyId")
                        .HasColumnType("int");

                    b.Property<int>("TherapyTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TherapyId");

                    b.HasIndex("TherapyTypeId");

                    b.ToTable("TherapyParts");
                });

            modelBuilder.Entity("minerva.planningfkt.models.TherapySlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModUser")
                        .HasColumnType("int");

                    b.Property<int?>("RescheduledToId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TherapistId")
                        .HasColumnType("int");

                    b.Property<int>("TherapyPartId")
                        .HasColumnType("int");

                    b.Property<int>("TimeSlot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("RescheduledToId");

                    b.HasIndex("TherapistId");

                    b.HasIndex("TherapyPartId");

                    b.HasIndex("Date", "TherapistId");

                    b.ToTable("TherapySlots");
                });

            modelBuilder.Entity("minerva.planningfkt.models.TherapyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviazione")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<int?>("MaxParallelFemale")
                        .HasColumnType("int");

                    b.Property<int?>("MaxParallelMale")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModUser")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("TherapyWeeklyFrequency")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TherapyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviazione = "Elettr",
                            Category = 0,
                            Color = 9489145,
                            Duration = 15,
                            IsActive = 1,
                            MaxParallelFemale = 4,
                            MaxParallelMale = 3,
                            ModDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModUser = 1,
                            Name = "Elettroterapia",
                            TherapyWeeklyFrequency = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Abbreviazione = "Ionof",
                            Category = 0,
                            Color = 16764032,
                            Duration = 20,
                            IsActive = 1,
                            MaxParallelFemale = 1,
                            MaxParallelMale = 1,
                            ModDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModUser = 1,
                            Name = "Ionoforesi",
                            TherapyWeeklyFrequency = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Abbreviazione = "Infrar",
                            Category = 0,
                            Color = 14842205,
                            Duration = 15,
                            IsActive = 1,
                            MaxParallelFemale = 1,
                            MaxParallelMale = 1,
                            ModDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModUser = 1,
                            Name = "Infrarossi",
                            TherapyWeeklyFrequency = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Abbreviazione = "Masso15",
                            Category = 0,
                            Color = 13538264,
                            Duration = 15,
                            IsActive = 1,
                            ModDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModUser = 1,
                            Name = "Massoterapia 15m",
                            TherapyWeeklyFrequency = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Abbreviazione = "Masso30",
                            Category = 0,
                            Color = 13538264,
                            Duration = 30,
                            IsActive = 1,
                            ModDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModUser = 1,
                            Name = "Massoterapia 30m",
                            TherapyWeeklyFrequency = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Abbreviazione = "Mez",
                            Category = 1,
                            Color = 16635957,
                            Duration = 60,
                            IsActive = 1,
                            ModDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModUser = 1,
                            Name = "Mezieres",
                            TherapyWeeklyFrequency = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Abbreviazione = "Isocin",
                            Category = 1,
                            Color = 13214247,
                            Duration = 30,
                            IsActive = 1,
                            ModDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModUser = 1,
                            Name = "Isocinetica",
                            TherapyWeeklyFrequency = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Abbreviazione = "Ried15",
                            Category = 1,
                            Color = 2541274,
                            Duration = 15,
                            IsActive = 1,
                            ModDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModUser = 1,
                            Name = "Rieducazione mot 15m",
                            TherapyWeeklyFrequency = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Abbreviazione = "Ried30",
                            Category = 1,
                            Color = 2541274,
                            Duration = 30,
                            IsActive = 1,
                            ModDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModUser = 1,
                            Name = "Rieducazione mot 30m",
                            TherapyWeeklyFrequency = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Abbreviazione = "Ried45",
                            Category = 1,
                            Color = 2541274,
                            Duration = 45,
                            IsActive = 1,
                            ModDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModUser = 1,
                            Name = "Rieducazione mot 45m",
                            TherapyWeeklyFrequency = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Abbreviazione = "Laser",
                            Category = 0,
                            Color = 8421376,
                            Duration = 15,
                            IsActive = 1,
                            MaxParallelFemale = 2,
                            MaxParallelMale = 2,
                            ModDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModUser = 1,
                            Name = "Laser",
                            TherapyWeeklyFrequency = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            Abbreviazione = "YAG",
                            Category = 0,
                            Color = 16485376,
                            Duration = 10,
                            IsActive = 1,
                            MaxParallelFemale = 1,
                            MaxParallelMale = 1,
                            ModDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModUser = 1,
                            Name = "Laser YAG",
                            TherapyWeeklyFrequency = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            Abbreviazione = "Magneto",
                            Category = 0,
                            Color = 7901340,
                            Duration = 30,
                            IsActive = 1,
                            MaxParallelFemale = 2,
                            MaxParallelMale = 2,
                            ModDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModUser = 1,
                            Name = "Magneto",
                            TherapyWeeklyFrequency = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            Abbreviazione = "UltraS",
                            Category = 0,
                            Color = 12433259,
                            Duration = 15,
                            IsActive = 1,
                            MaxParallelFemale = 1,
                            MaxParallelMale = 1,
                            ModDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModUser = 1,
                            Name = "Ultrasuoni",
                            TherapyWeeklyFrequency = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            Abbreviazione = "Tecar",
                            Category = 0,
                            Color = 9415055,
                            Duration = 30,
                            IsActive = 1,
                            MaxParallelFemale = 1,
                            MaxParallelMale = 1,
                            ModDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModUser = 1,
                            Name = "Tecar",
                            TherapyWeeklyFrequency = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            Abbreviazione = "OndeU",
                            Category = 1,
                            Color = 15094016,
                            Duration = 15,
                            IsActive = 1,
                            MaxParallelFemale = 1,
                            MaxParallelMale = 1,
                            ModDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModUser = 1,
                            Name = "Onde d'urto",
                            TherapyWeeklyFrequency = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            Abbreviazione = "ShockT",
                            Category = 0,
                            Color = 13990251,
                            Duration = 15,
                            IsActive = 1,
                            MaxParallelFemale = 1,
                            MaxParallelMale = 1,
                            ModDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModUser = 1,
                            Name = "Shock termico",
                            TherapyWeeklyFrequency = 7,
                            Type = 1
                        });
                });

            modelBuilder.Entity("minerva.planningfkt.models.Vacation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AMPM")
                        .HasColumnType("int");

                    b.Property<int?>("Day")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("IsSeeded")
                        .HasColumnType("int");

                    b.Property<int?>("IsYearIndependent")
                        .HasColumnType("int");

                    b.Property<int?>("Malattia")
                        .HasColumnType("int");

                    b.Property<int?>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int?>("TherapistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TherapistId");

                    b.ToTable("Vacations");
                });

            modelBuilder.Entity("minerva.planningfkt.models.TherapistAvailability", b =>
                {
                    b.HasOne("minerva.planningfkt.models.Therapist", null)
                        .WithMany()
                        .HasForeignKey("TherapistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("minerva.planningfkt.models.Therapy", b =>
                {
                    b.HasOne("minerva.planningfkt.models.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("minerva.planningfkt.models.TherapyPacket", b =>
                {
                    b.HasOne("minerva.planningfkt.models.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("minerva.planningfkt.models.TherapyPacketConfig", b =>
                {
                    b.HasOne("minerva.planningfkt.models.TherapyType", null)
                        .WithMany()
                        .HasForeignKey("TherapyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("minerva.planningfkt.models.TherapyPacketItem", b =>
                {
                    b.HasOne("minerva.planningfkt.models.TherapyPacket", null)
                        .WithMany()
                        .HasForeignKey("TherapyPacketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("minerva.planningfkt.models.TherapyType", null)
                        .WithMany()
                        .HasForeignKey("TherapyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("minerva.planningfkt.models.TherapyPart", b =>
                {
                    b.HasOne("minerva.planningfkt.models.Therapy", null)
                        .WithMany()
                        .HasForeignKey("TherapyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("minerva.planningfkt.models.TherapyType", null)
                        .WithMany()
                        .HasForeignKey("TherapyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("minerva.planningfkt.models.TherapySlot", b =>
                {
                    b.HasOne("minerva.planningfkt.models.TherapySlot", null)
                        .WithMany()
                        .HasForeignKey("RescheduledToId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("minerva.planningfkt.models.Therapist", null)
                        .WithMany()
                        .HasForeignKey("TherapistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("minerva.planningfkt.models.TherapyPart", null)
                        .WithMany()
                        .HasForeignKey("TherapyPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("minerva.planningfkt.models.Vacation", b =>
                {
                    b.HasOne("minerva.planningfkt.models.Therapist", null)
                        .WithMany()
                        .HasForeignKey("TherapistId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
